name: BoRS
version: '${project.version}'
main: io.github.narutopig.bors.Main
api-version: 1.18
authors: [ narutopig ]
description: Bunch of Random Stuff

commands:
  borsenchant:
    description: "Enchants an item with any custom enchant from this plugin (chaining supported)"
    usage: /borsenchant <enchant> <level>
    aliases:
      - borse
      - be

  grindstone:
    description: "Removes all custom enchantments from the current item in your hand"
    usage: /grindstone

  sethealth:
    description: "Sets the maximum health of a player"
    usage: /sethealth <player> <amount>
    permission: op

  updatelore:
    description: "Converts all enchants from the green text to the blue text (needed for the enchantments to work)"
    usage: /updatelore

  withdraw:
    description: "Turns health into heart items"
    usage: /withdraw <amount>