name: BoRS
version: '${project.version}'
main: Main
api-version: 1.18
authors: [ narutopig ]
description: Bunch of Random Stuff

commands:
  borsenchant:
    description: "Enchants an item with any custom enchant from this plugin (chaining supported)"
    usage: /borsenchant <enchant> <level>
    aliases:
      - borse
      - be

  sethealth:
    description: "Sets a player's max health"
    usage: /sethealth <player> <health>